language: python

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35

install:
  - pip install tox
  - pip install coveralls
  - pip install markdown

script:
    - tox
    - coverage run --source=mdx_embedly setup.py test
    - coverage report -m

after_success: coveralls
