language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
  - pip install tox
  - pip install coveralls

script:
    - tox
    - coverage --source=mdx_embedly  setup.py test
after_success: coveralls
